//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseInquire.CaseWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WO_SyncDataR", Namespace="http://schemas.datacontract.org/2004/07/WcfService_Support2")]
    [System.SerializableAttribute()]
    public partial class WO_SyncDataR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_CaseStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_CustBatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_CustCaseNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_DoctorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_EstimateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_OperationModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_OperationUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_OperationUserPwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_PartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_ReceiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_RelateCaseNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_RelateCaseStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_RouteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_StageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _Jobm_SystemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_AccountID {
            get {
                return this._Jobm_AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_AccountIDField, value) != true)) {
                    this._Jobm_AccountIDField = value;
                    this.RaisePropertyChanged("_Jobm_AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_CaseStep {
            get {
                return this._Jobm_CaseStepField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_CaseStepField, value) != true)) {
                    this._Jobm_CaseStepField = value;
                    this.RaisePropertyChanged("_Jobm_CaseStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_CustBatchID {
            get {
                return this._Jobm_CustBatchIDField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_CustBatchIDField, value) != true)) {
                    this._Jobm_CustBatchIDField = value;
                    this.RaisePropertyChanged("_Jobm_CustBatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_CustCaseNO {
            get {
                return this._Jobm_CustCaseNOField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_CustCaseNOField, value) != true)) {
                    this._Jobm_CustCaseNOField = value;
                    this.RaisePropertyChanged("_Jobm_CustCaseNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_DoctorName {
            get {
                return this._Jobm_DoctorNameField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_DoctorNameField, value) != true)) {
                    this._Jobm_DoctorNameField = value;
                    this.RaisePropertyChanged("_Jobm_DoctorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_EstimateDate {
            get {
                return this._Jobm_EstimateDateField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_EstimateDateField, value) != true)) {
                    this._Jobm_EstimateDateField = value;
                    this.RaisePropertyChanged("_Jobm_EstimateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_OperationMode {
            get {
                return this._Jobm_OperationModeField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_OperationModeField, value) != true)) {
                    this._Jobm_OperationModeField = value;
                    this.RaisePropertyChanged("_Jobm_OperationMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_OperationUserID {
            get {
                return this._Jobm_OperationUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_OperationUserIDField, value) != true)) {
                    this._Jobm_OperationUserIDField = value;
                    this.RaisePropertyChanged("_Jobm_OperationUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_OperationUserPwd {
            get {
                return this._Jobm_OperationUserPwdField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_OperationUserPwdField, value) != true)) {
                    this._Jobm_OperationUserPwdField = value;
                    this.RaisePropertyChanged("_Jobm_OperationUserPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_Partner {
            get {
                return this._Jobm_PartnerField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_PartnerField, value) != true)) {
                    this._Jobm_PartnerField = value;
                    this.RaisePropertyChanged("_Jobm_Partner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_Patient {
            get {
                return this._Jobm_PatientField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_PatientField, value) != true)) {
                    this._Jobm_PatientField = value;
                    this.RaisePropertyChanged("_Jobm_Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_ReceiveDate {
            get {
                return this._Jobm_ReceiveDateField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_ReceiveDateField, value) != true)) {
                    this._Jobm_ReceiveDateField = value;
                    this.RaisePropertyChanged("_Jobm_ReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_Region {
            get {
                return this._Jobm_RegionField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_RegionField, value) != true)) {
                    this._Jobm_RegionField = value;
                    this.RaisePropertyChanged("_Jobm_Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_RelateCaseNO {
            get {
                return this._Jobm_RelateCaseNOField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_RelateCaseNOField, value) != true)) {
                    this._Jobm_RelateCaseNOField = value;
                    this.RaisePropertyChanged("_Jobm_RelateCaseNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_RelateCaseStep {
            get {
                return this._Jobm_RelateCaseStepField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_RelateCaseStepField, value) != true)) {
                    this._Jobm_RelateCaseStepField = value;
                    this.RaisePropertyChanged("_Jobm_RelateCaseStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_RequestDate {
            get {
                return this._Jobm_RequestDateField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_RequestDateField, value) != true)) {
                    this._Jobm_RequestDateField = value;
                    this.RaisePropertyChanged("_Jobm_RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_Route {
            get {
                return this._Jobm_RouteField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_RouteField, value) != true)) {
                    this._Jobm_RouteField = value;
                    this.RaisePropertyChanged("_Jobm_Route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_Stage {
            get {
                return this._Jobm_StageField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_StageField, value) != true)) {
                    this._Jobm_StageField = value;
                    this.RaisePropertyChanged("_Jobm_Stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Jobm_SystemID {
            get {
                return this._Jobm_SystemIDField;
            }
            set {
                if ((object.ReferenceEquals(this._Jobm_SystemIDField, value) != true)) {
                    this._Jobm_SystemIDField = value;
                    this.RaisePropertyChanged("_Jobm_SystemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WO_ReturnInfoR", Namespace="http://schemas.datacontract.org/2004/07/WcfService_Support2")]
    [System.SerializableAttribute()]
    public partial class WO_ReturnInfoR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ReturnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ReturnCode {
            get {
                return this._ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this._ReturnCodeField, value) != true)) {
                    this._ReturnCodeField = value;
                    this.RaisePropertyChanged("_ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ReturnMessage {
            get {
                return this._ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this._ReturnMessageField, value) != true)) {
                    this._ReturnMessageField = value;
                    this.RaisePropertyChanged("_ReturnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CaseWS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncWorkOrderData", ReplyAction="http://tempuri.org/IService1/SyncWorkOrderDataResponse")]
        CaseInquire.CaseWS.WO_ReturnInfoR SyncWorkOrderData(CaseInquire.CaseWS.WO_SyncDataR WODataRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaseEstimateDate", ReplyAction="http://tempuri.org/IService1/GetCaseEstimateDateResponse")]
        string GetCaseEstimateDate(string Jobm_AccountID, string CaseNo, string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaseListByEstimateDate", ReplyAction="http://tempuri.org/IService1/GetCaseListByEstimateDateResponse")]
        string GetCaseListByEstimateDate(string Jobm_AccountID, string EstimateDate, string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPackingListByShipDate", ReplyAction="http://tempuri.org/IService1/GetPackingListByShipDateResponse")]
        string GetPackingListByShipDate(string Jobm_AccountID, string ShipDate, string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCateGory", ReplyAction="http://tempuri.org/IService1/GetCateGoryResponse")]
        string GetCateGory(string OperationUserID, string OperationUserPwd, string Jobm_AccountID, string Category_Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPriority", ReplyAction="http://tempuri.org/IService1/GetPriorityResponse")]
        string GetPriority(string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRepeatReason", ReplyAction="http://tempuri.org/IService1/GetRepeatReasonResponse")]
        string GetRepeatReason(string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserReportPartner", ReplyAction="http://tempuri.org/IService1/GetUserReportPartnerResponse")]
        string GetUserReportPartner(string OperationUserID, string OperationUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTitleTopic", ReplyAction="http://tempuri.org/IService1/GetTitleTopicResponse")]
        string GetTitleTopic(string OperationUserID, string OperationUserPwd, string JOBM_NO, string Title_Topic_Type, string CASE_FROM_ACCTID, string CASE_TO_ACCTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActiveLogReport", ReplyAction="http://tempuri.org/IService1/GetActiveLogReportResponse")]
        string GetActiveLogReport(string OperationUserID, string OperationUserPwd, string[] FromToAcctIdArr, string StartDateTime, string EndDateTime, string UserArr, string CaseNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitCaseListInfo", ReplyAction="http://tempuri.org/IService1/SubmitCaseListInfoResponse")]
        string SubmitCaseListInfo(
                    string OperationUserID, 
                    string OperationUserPwd, 
                    string CASE_FROM_ACCTID, 
                    string CASE_TO_ACCTID, 
                    string JOBM_NO, 
                    string CASE_CONTENT, 
                    string CASE_TOPIC, 
                    string CASE_ISNEW_TOPIC, 
                    string CASE_TITLE, 
                    string CASE_FROM_CATEGORY, 
                    string CASE_TO_CATEGORY, 
                    string CASE_PRIORITY, 
                    string CASE_FROM_SYSTEM, 
                    string CASE_FROM_KEYVALUE, 
                    string CASE_IS_REPEAT_REPLY, 
                    string CASE_REPEAT_REASON, 
                    string[] ARRAY_FILE_NAME, 
                    byte[][] ARRAY_FILE_STREAM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckReplyIsSynchronized", ReplyAction="http://tempuri.org/IService1/CheckReplyIsSynchronizedResponse")]
        string CheckReplyIsSynchronized(string from_system, string from_keyvalue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CaseInquire.CaseWS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CaseInquire.CaseWS.IService1>, CaseInquire.CaseWS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CaseInquire.CaseWS.WO_ReturnInfoR SyncWorkOrderData(CaseInquire.CaseWS.WO_SyncDataR WODataRecord) {
            return base.Channel.SyncWorkOrderData(WODataRecord);
        }
        
        public string GetCaseEstimateDate(string Jobm_AccountID, string CaseNo, string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetCaseEstimateDate(Jobm_AccountID, CaseNo, OperationUserID, OperationUserPwd);
        }
        
        public string GetCaseListByEstimateDate(string Jobm_AccountID, string EstimateDate, string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetCaseListByEstimateDate(Jobm_AccountID, EstimateDate, OperationUserID, OperationUserPwd);
        }
        
        public string GetPackingListByShipDate(string Jobm_AccountID, string ShipDate, string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetPackingListByShipDate(Jobm_AccountID, ShipDate, OperationUserID, OperationUserPwd);
        }
        
        public string GetCateGory(string OperationUserID, string OperationUserPwd, string Jobm_AccountID, string Category_Type) {
            return base.Channel.GetCateGory(OperationUserID, OperationUserPwd, Jobm_AccountID, Category_Type);
        }
        
        public string GetPriority(string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetPriority(OperationUserID, OperationUserPwd);
        }
        
        public string GetRepeatReason(string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetRepeatReason(OperationUserID, OperationUserPwd);
        }
        
        public string GetUserReportPartner(string OperationUserID, string OperationUserPwd) {
            return base.Channel.GetUserReportPartner(OperationUserID, OperationUserPwd);
        }
        
        public string GetTitleTopic(string OperationUserID, string OperationUserPwd, string JOBM_NO, string Title_Topic_Type, string CASE_FROM_ACCTID, string CASE_TO_ACCTID) {
            return base.Channel.GetTitleTopic(OperationUserID, OperationUserPwd, JOBM_NO, Title_Topic_Type, CASE_FROM_ACCTID, CASE_TO_ACCTID);
        }
        
        public string GetActiveLogReport(string OperationUserID, string OperationUserPwd, string[] FromToAcctIdArr, string StartDateTime, string EndDateTime, string UserArr, string CaseNo) {
            return base.Channel.GetActiveLogReport(OperationUserID, OperationUserPwd, FromToAcctIdArr, StartDateTime, EndDateTime, UserArr, CaseNo);
        }
        
        public string SubmitCaseListInfo(
                    string OperationUserID, 
                    string OperationUserPwd, 
                    string CASE_FROM_ACCTID, 
                    string CASE_TO_ACCTID, 
                    string JOBM_NO, 
                    string CASE_CONTENT, 
                    string CASE_TOPIC, 
                    string CASE_ISNEW_TOPIC, 
                    string CASE_TITLE, 
                    string CASE_FROM_CATEGORY, 
                    string CASE_TO_CATEGORY, 
                    string CASE_PRIORITY, 
                    string CASE_FROM_SYSTEM, 
                    string CASE_FROM_KEYVALUE, 
                    string CASE_IS_REPEAT_REPLY, 
                    string CASE_REPEAT_REASON, 
                    string[] ARRAY_FILE_NAME, 
                    byte[][] ARRAY_FILE_STREAM) {
            return base.Channel.SubmitCaseListInfo(OperationUserID, OperationUserPwd, CASE_FROM_ACCTID, CASE_TO_ACCTID, JOBM_NO, CASE_CONTENT, CASE_TOPIC, CASE_ISNEW_TOPIC, CASE_TITLE, CASE_FROM_CATEGORY, CASE_TO_CATEGORY, CASE_PRIORITY, CASE_FROM_SYSTEM, CASE_FROM_KEYVALUE, CASE_IS_REPEAT_REPLY, CASE_REPEAT_REASON, ARRAY_FILE_NAME, ARRAY_FILE_STREAM);
        }
        
        public string CheckReplyIsSynchronized(string from_system, string from_keyvalue) {
            return base.Channel.CheckReplyIsSynchronized(from_system, from_keyvalue);
        }
    }
}
